package com.github.filipt03.aquaristic_validator.model.types;

public enum RiskType {
    PHYSICAL_INJURY,
    WATER_QUALITY,
    OVERCROWDING,
    ESCAPE_RISK,
    PREDATION,
    SOCIAL_STRESS,
    TERRITORIAL_CONFLICT,
    TOXIC_FREE_AMMONIA,
    FLORA_DESTRUCTION,
    WRONG_PH,
    WRONG_TEMPERATURE,
    UNDERSIZED_FILTER_VOLUME,
    UNDERSIZED_FILTER_HEIGHT,
    UNDERSIZED_HEATER_VOLUME,
    MISSING_HEATER,
    WEAK_FILTRATION,
}
    