package rules;

import com.github.filipt03.aquaristic_validator.model.domain.Aquarium;
import com.github.filipt03.aquaristic_validator.model.domain.Fish;

import com.github.filipt03.aquaristic_validator.model.inference.Trait;
import com.github.filipt03.aquaristic_validator.model.inference.State;
import com.github.filipt03.aquaristic_validator.model.inference.Hazard;
import com.github.filipt03.aquaristic_validator.model.inference.Penalty;

import com.github.filipt03.aquaristic_validator.model.types.SubstrateType;
import com.github.filipt03.aquaristic_validator.model.types.StateType;
import com.github.filipt03.aquaristic_validator.model.types.TraitType;
import com.github.filipt03.aquaristic_validator.model.types.HazardType;
import com.github.filipt03.aquaristic_validator.model.types.PenaltyType;

global org.slf4j.Logger logger;

rule "Hazard: Physical Injury Risk on Bottom"
when
    $aq : Aquarium(substrateType == SubstrateType.SHARP_GRAVEL)
    $t  : Trait(traitType == TraitType.SENSITIVE_BARBELS, $speciesId : speciesId)
    $f  : Fish(speciesId == $speciesId)
    not Hazard(
        hazardType == HazardType.PHYSICAL_INJURY,
        affectedSpeciesId == $speciesId
    )
then
    String desc = $f.getSpecies() + " has sensitive barbels and sharp gravel will cause physical injuries and infections.";
    insert(new Hazard(HazardType.PHYSICAL_INJURY, $speciesId, desc));
    logger.trace("[{}] Hazard Detected: PHYSICAL_INJURY for {}", drools.getRule().getName(), $f.getSpecies());
end

rule "Hazard: Overstocking Stress"
when
    State(stateType == StateType.HIGH_BIOLOAD)

    not Hazard(hazardType == HazardType.OVERCROWDING)
then
    insert(
        new Hazard(
            HazardType.OVERCROWDING,
            -1,
            "Aquarium is overstocked and fish may suffer chronic stress."
        )
    );
    logger.trace("[{}] Hazard Detected: OVERCROWDING", drools.getRule().getName());
end