
package rules;

import com.github.filipt03.aquaristic_validator.model.domain.Aquarium;
import com.github.filipt03.aquaristic_validator.model.domain.Fish;

import com.github.filipt03.aquaristic_validator.model.inference.Trait;
import com.github.filipt03.aquaristic_validator.model.inference.State;
import com.github.filipt03.aquaristic_validator.model.inference.Hazard;
import com.github.filipt03.aquaristic_validator.model.inference.Penalty;

import com.github.filipt03.aquaristic_validator.model.types.SubstrateType;
import com.github.filipt03.aquaristic_validator.model.types.StateType;
import com.github.filipt03.aquaristic_validator.model.types.TraitType;
import com.github.filipt03.aquaristic_validator.model.types.RiskType;

global org.slf4j.Logger logger;

rule "Penalty: Penalize Physical Injury"
when
    $h : Hazard(type == RiskType.PHYSICAL_INJURY, $speciesId : affectedSpeciesId, $desc : description)
    not Penalty(type == RiskType.PHYSICAL_INJURY, affectedSpeciesId == $speciesId)
then
    insert(new Penalty(
        RiskType.PHYSICAL_INJURY, $speciesId, 15,
        "CRITICAL (Physical Injury): " + $desc
    ));
    logger.trace("[{}] Penalty Added: Score decreased by 15.", drools.getRule().getName());
end

rule "Penalty: Penalize Overcrowding"
when
    $h : Hazard(type == RiskType.OVERCROWDING, $desc : description)
    not Penalty(type == RiskType.OVERCROWDING, affectedSpeciesId == -1)
then
    insert(new Penalty(
        RiskType.OVERCROWDING, -1, 10,
        "MAJOR (Overcrowding): " + $desc
    ));
    logger.trace("[{}] Penalty Added: Score decreased by 10.", drools.getRule().getName());
end

rule "Penalty: Penalize Undersized Filter Volume"
when
    $h : Hazard(type == RiskType.UNDERSIZED_FILTER_VOLUME, $desc : description)
    not Penalty(type == RiskType.UNDERSIZED_FILTER_VOLUME)
then
    insert(new Penalty(RiskType.UNDERSIZED_FILTER_VOLUME, -1, 10, "MAJOR (Undersized Filter Volume): " + $desc));
    logger.trace("[{}] Penalty Added: Score decreased by 10.", drools.getRule().getName());
end

rule "Penalty: Penalize Undersized Filter Height"
when
    $h : Hazard(type == RiskType.UNDERSIZED_FILTER_HEIGHT, $desc : description)
    not Penalty(type == RiskType.UNDERSIZED_FILTER_HEIGHT)
then
    insert(new Penalty(RiskType.UNDERSIZED_FILTER_HEIGHT, -1, 10, "MAJOR (Undersized Filter Height): " + $desc));
    logger.trace("[{}] Penalty Added: Score decreased by 10.", drools.getRule().getName());
end

rule "Penalty: Penalize Undersized Heater"
when
    $h : Hazard(type == RiskType.UNDERSIZED_HEATER_VOLUME, $desc : description)
    not Penalty(type == RiskType.UNDERSIZED_HEATER_VOLUME)
then
    insert(new Penalty(RiskType.UNDERSIZED_HEATER_VOLUME, -1, 10, "MAJOR (Undersized Heater): " + $desc));
    logger.trace("[{}] Penalty Added: Score decreased by 10.", drools.getRule().getName());
end

rule "Penalty: Penalize Wrong pH Minor"
when
    $h : Hazard(
        type == RiskType.WRONG_PH, $speciesId : affectedSpeciesId, $desc : description, $severity : severity,
        $severity > 0, $severity <= 0.5
    )
    not Penalty(type == RiskType.WRONG_PH, affectedSpeciesId == $speciesId)
then
    insert(new Penalty(
        RiskType.WRONG_PH, $speciesId, 3,
        "MINOR (pH wrong by " + $severity + "): " + $desc
    ));
    logger.trace("[{}] Penalty Added: Score decreased by 3.", drools.getRule().getName());
end

rule "Penalty: Penalize Wrong pH Moderate"
when
    $h : Hazard(
        type == RiskType.WRONG_PH, $speciesId : affectedSpeciesId, $desc : description, $severity : severity,
        $severity > 0.5, $severity <= 1.0
    )
    not Penalty(type == RiskType.WRONG_PH, affectedSpeciesId == $speciesId)
then
    insert(new Penalty(
        RiskType.WRONG_PH, $speciesId, 6,
        "MODERATE (pH wrong by " + $severity + "): " + $desc
    ));
    logger.trace("[{}] Penalty Added: Score decreased by 6.", drools.getRule().getName());
end

rule "Penalty: Penalize Wrong pH Major"
when
    $h : Hazard(
        type == RiskType.WRONG_PH, $speciesId : affectedSpeciesId, $desc : description, $severity : severity,
        $severity > 1.0, $severity <= 2.0
    )
    not Penalty(type == RiskType.WRONG_PH, affectedSpeciesId == $speciesId)
then
    insert(new Penalty(
        RiskType.WRONG_PH, $speciesId, 9,
        "MAJOR (pH wrong by " + $severity + "): " + $desc
    ));
    logger.trace("[{}] Penalty Added: Score decreased by 9.", drools.getRule().getName());
end

rule "Penalty: Penalize Wrong pH Critical"
when
    $h : Hazard(
        type == RiskType.WRONG_PH, $speciesId : affectedSpeciesId, $desc : description, $severity : severity,
        $severity > 2.0
    )
    not Penalty(type == RiskType.WRONG_PH, affectedSpeciesId == $speciesId)
then
    insert(new Penalty(
        RiskType.WRONG_PH, $speciesId, 15,
        "CRITICAL (pH wrong by " + $severity + "): " + $desc
    ));
    logger.trace("[{}] Penalty Added: Score decreased by 15.", drools.getRule().getName());
end

rule "Penalty: Penalize Wrong Temperature Minor"
when
    $h : Hazard(
        type == RiskType.WRONG_TEMPERATURE, $speciesId : affectedSpeciesId, $desc : description, $severity : severity,
        $severity > 0, $severity <= 2.0
    )
    not Penalty(type == RiskType.WRONG_TEMPERATURE, affectedSpeciesId == $speciesId)
then
    insert(new Penalty(
        RiskType.WRONG_TEMPERATURE, $speciesId, 3,
        "MINOR (Temperature wrong by " + $severity + "): " + $desc
    ));
    logger.trace("[{}] Penalty Added: Score decreased by 3.", drools.getRule().getName());
end

rule "Penalty: Penalize Wrong Temperature Moderate"
when
    $h : Hazard(
        type == RiskType.WRONG_TEMPERATURE, $speciesId : affectedSpeciesId, $desc : description, $severity : severity,
        $severity > 2.0, $severity <= 4.0
    )
    not Penalty(type == RiskType.WRONG_TEMPERATURE, affectedSpeciesId == $speciesId)
then
    insert(new Penalty(
        RiskType.WRONG_TEMPERATURE, $speciesId, 6,
        "MODERATE (Temperature wrong by " + $severity + "): " + $desc
    ));
    logger.trace("[{}] Penalty Added: Score decreased by 6.", drools.getRule().getName());
end

rule "Penalty: Penalize Wrong Temperature Major"
when
    $h : Hazard(
        type == RiskType.WRONG_TEMPERATURE, $speciesId : affectedSpeciesId, $desc : description, $severity : severity,
        $severity > 4.0, $severity <= 6.0
    )
    not Penalty(type == RiskType.WRONG_TEMPERATURE, affectedSpeciesId == $speciesId)
then
    insert(new Penalty(
        RiskType.WRONG_TEMPERATURE, $speciesId, 9,
        "MAJOR (Temperature wrong by " + $severity + "): " + $desc
    ));
    logger.trace("[{}] Penalty Added: Score decreased by 9.", drools.getRule().getName());
end

rule "Penalty: Penalize Wrong Temperature Critical"
when
    $h : Hazard(
        type == RiskType.WRONG_TEMPERATURE, $speciesId : affectedSpeciesId, $desc : description, $severity : severity,
        $severity > 6.0
    )
    not Penalty(type == RiskType.WRONG_TEMPERATURE, affectedSpeciesId == $speciesId)
then
    insert(new Penalty(
        RiskType.WRONG_TEMPERATURE, $speciesId, 15,
        "CRITICAL (Temperature wrong by " + $severity + "): " + $desc
    ));
    logger.trace("[{}] Penalty Added: Score decreased by 15.", drools.getRule().getName());
end